name: Hostile
description: Custom Hostile Mobs
author: StarTux
version: 0.1
main: com.winthier.hostile.HostilePlugin
depend: [ Custom, GenericEvents, Ore ]
commands:
  hostile:
    description: Admin interface
    permission: hostile.hostile
    usage: |-
      /hostile info [player]
      /hostile level <level>
permissions:
  hostile.hostile:
    description: Use /hostile
